// COLUMNAS
GET http://localhost:3000/api/columnas

POST http://localhost:3000/api/columnas HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd120470",
    "material": "Madera",
    "fechaAdquisicion": "2003-03-09",
    "fechaInstalacion": "2004-05-24"
}

POST http://localhost:3000/api/columnas/findMany HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd120470",
    "material": "Madera",
    "fechaAdquisicion": "2003-03-09",
    "fechaInstalacion": "2004-05-24",
    "ids": [2, 3]
}

// LUMINARIAS
GET http://localhost:3000/api/luminarias

POST http://localhost:3000/api/luminarias HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd120740",
    "marca": "Osram",
	"tecnologia": "Sodio",
	"potencia": "900",
    "fechaAdquisicion": "2004-04-08",
    "fechaInstalacion": "2004-05-24"
}

// EQUIPOS AUXILIARES
GET http://localhost:3000/api/equiposAuxiliares

POST http://localhost:3000/api/equiposAuxiliares HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd123510",
    "marca": "Osram",
	"tipo": "Driver",
    "fechaAdquisicion": "2023-03-19",
    "fechaInstalacion": "2025-03-20"
}

// SERVICIOS
GET http://localhost:3000/api/serviciosLuz

POST http://localhost:3000/api/serviciosLuz HTTP/1.1
content-type: application/json

{
    "luminarias": [2],
    "equipoAuxiliar": [3],
    "columna": 2,
    "fechaInstalacion": "2025-03-20"
}
