// COLUMNAS
GET http://localhost:3000/api/columnas

POST http://localhost:3000/api/columnas HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd123495",
    "material": "Acero",
    "fechaAdquisicion": "2024-05-19",
    "fechaInstalacion": "2024-05-24",
    "fechaRemocion": "2025-01-19"
}

PATCH http://localhost:3000/api/columnas/10 HTTP/1.1
content-type: application/json

{
    "fechaRemocion": "2024-05-19"
}

POST http://localhost:3000/api/columnas/findMany HTTP/1.1
content-type: application/json

{
    "fechaInstalacion": "1970-02-02"
}

// LUMINARIAS
GET http://localhost:3000/api/luminarias

POST http://localhost:3000/api/luminarias HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd125764",
    "marca": "Philips",
	"tecnologia": "LED",
	"potencia": "500",
    "fechaAdquisicion": "2024-06-29",
    "fechaInstalacion": "2025-05-24"
}

// EQUIPOS AUXILIARES
GET http://localhost:3000/api/equiposAuxiliares/

POST http://localhost:3000/api/equiposAuxiliares HTTP/1.1
content-type: application/json

{
    "nroSerie": "abcd123534",
    "marca": "Philips",
	"tipo": "Driver",
    "fechaAdquisicion": "2024-06-29",
    "fechaInstalacion": "2025-03-20"
}

// SERVICIOS
GET http://localhost:3000/api/serviciosLuz

POST http://localhost:3000/api/serviciosLuz HTTP/1.1
content-type: application/json

{
    "luminarias": [20],
    "equipoAuxiliar": [15],
    "columna": 15,
    "fechaInstalacion": "2025-05-21"
}

PATCH http://localhost:3000/api/serviciosLuz/13 HTTP/1.1
content-type: application/json

{
    "columna": null
}

// EMPLEADOS
GET http://localhost:3000/api/empleados/3

GET http://localhost:3000/api/empleados/ HTTP/1.1
content-type: application/json
Authorization: 

{
    "dni": "19550645",
    "apellido": "Juan",
    "nombre": "Jose",
    "email": "juanjo@mail.com",
    "telefono": "3415654785",
    "fechaIngreso": "2022-06-30",
    "rol": "Empleado"
}

POST http://localhost:3000/api/empleados/login HTTP/1.1
content-type: application/json

{
    "dni": "19550640",
    "clave": "margamarga"
}
